[project]
name = "advent-of-code"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "pulp>=3.3.0",
    "shapely>=2.1.2",
]

[tool.pytest.ini_options]
python_files = ["test.py", "test_*.py", "*_test.py"]
